//! The pages.
//!
//! Hand-built strings rather than a template engine: the whole site is five
//! page shapes, and a dependency that renders them would be larger than they
//! are. Every page is complete HTML with its own metadata, because the unit
//! that gets shared is one entry, not the site.

use cairns_core::log::{Log, LogEntry};
use pulldown_cmark::{Options, Parser, html};
use std::collections::BTreeMap;
use std::fmt::Write as _;

pub fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(ch),
        }
    }
    out
}

fn options() -> Options {
    Options::ENABLE_TABLES | Options::ENABLE_STRIKETHROUGH | Options::ENABLE_FOOTNOTES
}

fn markdown(text: &str) -> String {
    let mut out = String::new();
    html::push_html(&mut out, Parser::new_ext(text, options()));
    out
}

/// The prose alone: the entry's own `# N. Title` and its open-question trailer
/// are rendered by the page, in their own places, so they are cut from here
/// rather than appearing twice.
fn prose(entry: &LogEntry) -> &str {
    let text = entry.body.as_str();
    let text = match text.strip_prefix("# ") {
        Some(rest) => rest.split_once('\n').map(|(_, rest)| rest).unwrap_or(""),
        None => text,
    };
    let cut = text
        .match_indices(cairns_core::entry::STILL_UNKNOWN)
        .map(|(at, _)| at)
        .filter(|at| *at == 0 || text[..*at].ends_with('\n'))
        .last()
        .unwrap_or(text.len());
    text[..cut].trim()
}

/// Markdown reduced to its text, for anywhere markup would be shown literally
/// rather than rendered - a link preview, a feed summary, a list blurb.
pub fn plain_md(text: &str) -> String {
    use pulldown_cmark::Event;
    let mut out = String::new();
    for event in Parser::new_ext(text, options()) {
        match event {
            Event::Text(text) | Event::Code(text) => out.push_str(&text),
            Event::SoftBreak | Event::HardBreak => out.push(' '),
            _ => {}
        }
    }
    out.trim().to_string()
}

/// An entry's prose as HTML, for the feed.
pub fn body_html(entry: &LogEntry) -> String {
    markdown(prose(entry))
}

/// An entry's body as plain text, for the search index.
pub fn plain(entry: &LogEntry) -> String {
    use pulldown_cmark::Event;
    let mut out = String::new();
    for event in Parser::new_ext(prose(entry), options()) {
        match event {
            Event::Text(text) | Event::Code(text) => {
                out.push_str(&text);
                out.push(' ');
            }
            Event::SoftBreak | Event::HardBreak => out.push(' '),
            _ => {}
        }
    }
    out
}

/// The page shell. `rel` is the path back to the site root from this page, so
/// one renderer serves the root pages and the entry pages alike.
fn shell(log: &Log, title: &str, description: &str, url: &str, rel: &str, body: &str) -> String {
    let base = log.project.base_url.trim_end_matches('/');
    let mut out = String::new();
    let _ = write!(
        out,
        r#"<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{description}">
<link rel="canonical" href="{url}">
<meta property="og:type" content="article">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{description}">
<meta property="og:url" content="{url}">
<meta property="og:site_name" content="{site}">
<meta name="twitter:card" content="summary">
<link rel="alternate" type="application/atom+xml" title="{site}" href="{base}/feed.xml">
<link rel="stylesheet" href="{rel}style.css">
</head>
<body>
<div class="wrap">
<header class="masthead">
<h1><a href="{rel}">{site}</a></h1>
{tagline}<nav><a href="{rel}">Entries</a><a href="{rel}open/">Open questions</a><a href="{rel}feed.xml">Feed</a></nav>
</header>
{body}
<footer>
<p>A worklog. Newest last, append-only - a claim that turned out wrong is
overturned by a later entry, never by editing the original.
Generated by <a href="https://github.com/Toyz/cairns">cairns</a>.</p>
</footer>
</div>
</body>
</html>
"#,
        title = escape(title),
        description = escape(description),
        url = escape(url),
        site = escape(&log.project.name),
        tagline = if log.project.description.is_empty() {
            String::new()
        } else {
            format!("<p>{}</p>\n", escape(&log.project.description))
        },
        base = escape(base),
    );
    out
}

fn path_of(entry: &LogEntry) -> String {
    format!("{}-{}", entry.number, entry.slug)
}

/// The index: every entry, with the chips and the search box over it.
pub fn home(log: &Log) -> String {
    let base = log.project.base_url.trim_end_matches('/');
    let mut body = String::new();

    body.push_str("<div class=\"controls\">\n");
    let _ = write!(
        body,
        "<input type=\"search\" id=\"q\" placeholder=\"Search {} entries\" \
         autocomplete=\"off\" spellcheck=\"false\">\n<span id=\"status\"></span>\n",
        log.entries.len()
    );
    body.push_str("</div>\n<div class=\"chips\">\n");
    for area in log.areas.iter().filter(|area| area.count > 0) {
        let _ = writeln!(
            body,
            "<button class=\"chip\" data-area=\"{name}\" aria-pressed=\"false\" \
             title=\"{about}\">{name}<span class=\"count\">{count}</span></button>",
            name = escape(&area.name),
            about = escape(&area.about),
            count = area.count
        );
    }
    body.push_str("</div>\n<ul class=\"entries\" id=\"entries\">\n");

    for entry in &log.entries {
        let _ = write!(
            body,
            "<li data-n=\"{n}\" data-areas=\"{areas}\">\n\
             <h2><span class=\"no\">{n}</span><a href=\"{path}/\">{title}</a></h2>\n",
            n = entry.number,
            areas = escape(&entry.areas.join(" ")),
            path = escape(&path_of(entry)),
            title = escape(&entry.title)
        );
        if let Some(summary) = &entry.summary {
            let _ = writeln!(body, "<p>{}</p>", escape(&plain_md(summary)));
        }
        let _ = write!(
            body,
            "<p class=\"meta\">{date} &middot; {areas}</p>\n</li>\n",
            date = entry.date,
            areas = escape(&entry.areas.join(", "))
        );
    }

    body.push_str("</ul>\n<script src=\"search.js\" defer></script>\n");

    let description = if log.project.description.is_empty() {
        format!("{} entries.", log.entries.len())
    } else {
        plain_md(&log.project.description)
    };
    shell(log, &log.project.name, &description, base, "./", &body)
}

/// One entry, with its corrections, its open question, and its neighbours.
pub fn entry(log: &Log, at: usize, by_number: &BTreeMap<u32, &LogEntry>) -> String {
    let this = &log.entries[at];
    let mut body = String::from("<article>\n");

    let _ = writeln!(body, "<h1>{}</h1>", escape(&this.title));
    let _ = write!(body, "<p class=\"dateline\">{} &middot; ", this.date);
    for area in &this.areas {
        let _ = write!(body, "<span class=\"chip\">{}</span> ", escape(area));
    }
    body.push_str("</p>\n");

    // The notice is the whole reason an append-only log is safe to read: a
    // reader standing on an overturned claim is told so before the prose.
    let link = |number: u32| match by_number.get(&number) {
        Some(other) => format!(
            "<a href=\"../{}/\">{}</a>",
            escape(&path_of(other)),
            escape(&other.title)
        ),
        None => format!("entry {number}"),
    };
    if !this.superseded_by.is_empty() || !this.supersedes.is_empty() {
        body.push_str("<div class=\"notice\">\n");
        if !this.superseded_by.is_empty() {
            let who: Vec<String> = this.superseded_by.iter().map(|n| link(*n)).collect();
            let _ = writeln!(
                body,
                "<p><strong>Revisited later.</strong> Something claimed here was \
                 corrected by {}.</p>",
                who.join(", ")
            );
        }
        if !this.supersedes.is_empty() {
            let who: Vec<String> = this.supersedes.iter().map(|n| link(*n)).collect();
            let _ = writeln!(body, "<p>This entry revisits {}.</p>", who.join(", "));
        }
        body.push_str("</div>\n");
    }

    body.push_str(&markdown(prose(this)));

    if let Some(unknown) = &this.still_unknown {
        let _ = writeln!(
            body,
            "<div class=\"unknown\"><strong>Still unknown</strong>{}</div>",
            markdown(unknown)
        );
    }
    body.push_str("</article>\n<nav class=\"pager\">\n");
    if at > 0 {
        let previous = &log.entries[at - 1];
        let _ = writeln!(
            body,
            "<a class=\"prev\" href=\"../{}/\">&larr; {}</a>",
            escape(&path_of(previous)),
            escape(&previous.title)
        );
    }
    if at + 1 < log.entries.len() {
        let next = &log.entries[at + 1];
        let _ = writeln!(
            body,
            "<a class=\"next\" href=\"../{}/\">{} &rarr;</a>",
            escape(&path_of(next)),
            escape(&next.title)
        );
    }
    body.push_str("</nav>\n");

    let description = plain_md(this.summary.as_deref().unwrap_or(&this.title));
    let title = format!("{}. {}", this.number, this.title);
    shell(log, &title, &description, &this.url, "../", &body)
}

/// Everything the log has not closed out, in one place.
pub fn open_questions(log: &Log) -> String {
    let base = log.project.base_url.trim_end_matches('/');
    let by_number: BTreeMap<u32, &LogEntry> = log
        .entries
        .iter()
        .map(|entry| (entry.number, entry))
        .collect();

    let mut body = String::from("<article>\n<h1>Open questions</h1>\n");
    let _ = writeln!(
        body,
        "<p class=\"dateline\">{} of {} entries have something still unresolved.</p>",
        log.open_questions.len(),
        log.entries.len()
    );

    if log.open_questions.is_empty() {
        body.push_str("<p class=\"empty\">Nothing open.</p>\n");
    } else {
        body.push_str("<ul class=\"questions\">\n");
        for question in &log.open_questions {
            let path = by_number
                .get(&question.entry)
                .map(|entry| path_of(entry))
                .unwrap_or_default();
            let _ = writeln!(
                body,
                "<li><a class=\"no\" href=\"../{path}/\">{}</a><div>{}</div></li>",
                question.entry,
                markdown(&question.text)
            );
        }
        body.push_str("</ul>\n");
    }
    body.push_str("</article>\n");

    shell(
        log,
        &format!("Open questions - {}", log.project.name),
        "What this log has not closed out.",
        &format!("{base}/open/"),
        "../",
        &body,
    )
}
