//! The renderer.
//!
//! It takes a [`Log`] and nothing else. It never reads an entry file, never
//! looks at `cairns.toml`, and never touches the filesystem - it returns bytes
//! and lets the caller decide where they go, which is what makes a publish
//! target and a local build the same code path.

pub mod feed;
pub mod html;

use cairns_core::Log;
use serde::Serialize;

/// One file in a rendered payload, at a path relative to the payload root.
#[derive(Debug, Clone)]
pub struct OutputFile {
    pub path: String,
    pub bytes: Vec<u8>,
}

/// A rendered payload, ready to hand to any publish target.
#[derive(Debug, Clone, Default)]
pub struct Rendered {
    pub files: Vec<OutputFile>,
}

impl Rendered {
    fn push(&mut self, path: impl Into<String>, bytes: impl Into<Vec<u8>>) {
        self.files.push(OutputFile {
            path: path.into(),
            bytes: bytes.into(),
        });
    }
}

/// One row of the search index.
#[derive(Serialize)]
struct Searchable {
    n: u32,
    /// Title, summary, areas and body, lower-cased into one haystack. One field
    /// because the page does one thing with it.
    t: String,
}

/// Render the whole payload: the site, the feed, and the canonical document it
/// was all built from.
///
/// Entry pages are written as `{number}-{slug}/index.html`, so the URLs in
/// `log.json` resolve on any static host without rewrite rules.
pub fn render(log: &Log) -> Result<Rendered, serde_json::Error> {
    let mut rendered = Rendered::default();

    rendered.push("log.json", serde_json::to_vec_pretty(log)?);
    rendered.push("style.css", include_str!("assets/style.css"));
    rendered.push("search.js", include_str!("assets/search.js"));
    rendered.push("index.html", html::home(log));
    rendered.push("open/index.html", html::open_questions(log));
    if log.readme.is_some() {
        rendered.push("about/index.html", html::about(log));
    }
    rendered.push("feed.xml", feed::atom(log));

    let by_number = log
        .entries
        .iter()
        .map(|entry| (entry.number, entry))
        .collect();
    for (at, entry) in log.entries.iter().enumerate() {
        rendered.push(
            format!("{}-{}/index.html", entry.number, entry.slug),
            html::entry(log, at, &by_number),
        );
    }

    let searchable: Vec<Searchable> = log
        .entries
        .iter()
        .map(|entry| Searchable {
            n: entry.number,
            t: format!(
                "{} {} {} {}",
                entry.title,
                entry.summary.clone().unwrap_or_default(),
                entry.areas.join(" "),
                html::plain(entry)
            )
            .to_lowercase(),
        })
        .collect();
    rendered.push("search.json", serde_json::to_vec(&searchable)?);

    Ok(rendered)
}

/// Render the index - `WORKLOG.md` - from the log.
///
/// Generated, and named as such in its own first lines, because the failure
/// mode it exists to prevent is somebody editing it to match what they think
/// the entries say.
pub fn render_index(log: &Log, header: Option<&str>) -> String {
    let mut out = String::new();

    match header {
        Some(written) => {
            out.push_str(written.trim_end());
            out.push_str("\n\n");
        }
        None => {
            out.push_str("# Worklog\n\n");
            if !log.project.description.is_empty() {
                out.push_str(&log.project.description);
                out.push_str("\n\n");
            }
            out.push_str(
                "One file per entry, newest at the bottom. This index is generated by \
                 `cairns index` - edit the entries, not this file.\n\n",
            );
        }
    }

    // Alphabetical, not declared order: this line is a tally, and a tally reads
    // better sorted by the name you would look for.
    let mut counted: Vec<_> = log.areas.iter().filter(|area| area.count > 0).collect();
    counted.sort_by(|a, b| a.name.cmp(&b.name));
    let tally = counted
        .iter()
        .map(|area| format!("{} {}", area.name, area.count))
        .collect::<Vec<_>>()
        .join(", ");
    let total = log.entries.len();
    let plural = if total == 1 { "entry" } else { "entries" };
    out.push_str(&format!("{total} {plural}: {tally}.\n\n"));

    out.push_str("| # | Entry | Date | Area |\n| ---: | --- | --- | --- |\n");
    for entry in &log.entries {
        let title = entry.title.replace('|', "\\|");
        out.push_str(&format!(
            "| {} | [{title}]({}) | {} | {} |\n",
            entry.number,
            entry.path,
            entry.date,
            entry.areas.join(", ")
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use cairns_core::{Config, Entry, RawEntry};

    fn log(entries: &[(&str, &str)]) -> Log {
        let config = Config::parse(
            r#"
            spec_version = 1
            [project]
            name = "A Project"
            slug = "a-project"
            description = "Testing."
            [site]
            base_url = "https://example.com/a-project/"
            [[area]]
            name = "spec"
            [[area]]
            name = "core"
            "#,
        )
        .unwrap();

        let parsed: Vec<Entry> = entries
            .iter()
            .enumerate()
            .map(|(at, (front, body))| {
                let number = at + 1;
                let text = format!("---\n{front}\n---\n\n# {number}. Title {number}\n\n{body}\n");
                Entry::parse(&RawEntry {
                    path: format!("worklog/{number:04}-title-{number}.md"),
                    bytes: text.into_bytes(),
                })
                .unwrap()
            })
            .collect();
        Log::build(&config, parsed, None)
    }

    fn simple() -> Log {
        log(&[(
            "number: 1\ntitle: Title 1\ndate: 2026-09-20\narea: spec",
            "Some prose.\n\n**Still unknown:** whether it works.",
        )])
    }

    #[test]
    fn a_payload_carries_the_site_and_the_document_it_came_from() {
        let rendered = render(&simple()).unwrap();
        let files: Vec<&str> = rendered.files.iter().map(|f| f.path.as_str()).collect();
        for wanted in [
            "log.json",
            "index.html",
            "style.css",
            "search.js",
            "search.json",
            "feed.xml",
            "open/index.html",
            "1-title-1/index.html",
        ] {
            assert!(files.contains(&wanted), "{wanted} missing from {files:?}");
        }
    }

    #[test]
    fn the_entry_page_renders_prose_once_and_the_trailer_separately() {
        let built = simple();
        let by_number = built.entries.iter().map(|e| (e.number, e)).collect();
        let page = html::entry(&built, 0, &by_number);
        // Once in the article. It also appears in the two meta descriptions,
        // because the summary is derived from the first sentence - which is
        // the point of deriving it, not a duplicate.
        assert_eq!(page.matches("<p>Some prose.</p>").count(), 1);
        assert_eq!(
            page.matches("og:description\" content=\"Some prose.")
                .count(),
            1
        );
        // One heading for the site, one for the entry - none from the body.
        assert_eq!(page.matches("<h1>").count(), 2);
        assert!(page.contains("class=\"unknown\""));
        assert!(page.contains("whether it works."));
        assert!(
            !page.contains("**Still unknown:**"),
            "the marker leaked into the page"
        );
    }

    #[test]
    fn markdown_tables_and_code_render() {
        let built = log(&[(
            "number: 1\ntitle: Title 1\ndate: 2026-09-20\narea: spec",
            "| a | b |\n| --- | --- |\n| 1 | 2 |\n\n```\ncode\n```",
        )]);
        let by_number = built.entries.iter().map(|e| (e.number, e)).collect();
        let page = html::entry(&built, 0, &by_number);
        assert!(page.contains("<table>"), "tables are not enabled");
        assert!(page.contains("<pre>"), "code blocks are not rendering");
    }

    #[test]
    fn a_title_with_markup_in_it_cannot_escape_an_attribute() {
        let built = log(&[(
            "number: 1\ntitle: A \"quoted\" <script> & co\ndate: 2026-09-20\narea: spec",
            "Prose.",
        )]);
        let by_number = built.entries.iter().map(|e| (e.number, e)).collect();
        let page = html::entry(&built, 0, &by_number);
        assert!(
            !page.contains("<script>"),
            "an unescaped tag reached the page"
        );
        assert!(page.contains("&quot;quoted&quot;"));
    }

    #[test]
    fn a_correction_is_announced_on_the_entry_it_corrects() {
        let built = log(&[
            (
                "number: 1\ntitle: Title 1\ndate: 2026-09-20\narea: spec",
                "The wrong claim.",
            ),
            (
                "number: 2\ntitle: Title 2\ndate: 2026-09-21\narea: spec\nsupersedes: 1",
                "The right one.",
            ),
        ]);
        let by_number: std::collections::BTreeMap<_, _> =
            built.entries.iter().map(|e| (e.number, e)).collect();

        let overturned = html::entry(&built, 0, &by_number);
        assert!(overturned.contains("Revisited later"));
        assert!(overturned.contains("../2-title-2/"));

        let correcting = html::entry(&built, 1, &by_number);
        assert!(correcting.contains("revisits"));
        assert!(correcting.contains("../1-title-1/"));
    }

    #[test]
    fn the_feed_is_capped_and_points_at_the_whole_log() {
        let many: Vec<(String, String)> = (1..=30)
            .map(|n| {
                (
                    format!("number: {n}\ntitle: Title {n}\ndate: 2026-09-20\narea: spec"),
                    "Prose.".to_string(),
                )
            })
            .collect();
        let borrowed: Vec<(&str, &str)> =
            many.iter().map(|(f, b)| (f.as_str(), b.as_str())).collect();
        let xml = feed::atom(&log(&borrowed));
        assert_eq!(xml.matches("<entry>").count(), feed::FEED_ENTRIES);
        assert!(
            xml.contains("log.json"),
            "nothing points at the complete document"
        );
    }
}
