//! The renderer.
//!
//! It takes a [`Log`] and nothing else. It never reads an entry file, never
//! looks at `cairns.toml`, and never touches the filesystem - it returns bytes
//! and lets the caller decide where they go, which is what makes a publish
//! target and a local build the same code path.

pub mod feed;
pub mod html;
pub mod icon;

use cairns_core::Log;
use serde::Serialize;

/// One file in a rendered payload, at a path relative to the payload root.
#[derive(Debug, Clone)]
pub struct OutputFile {
    pub path: String,
    pub bytes: Vec<u8>,
}

/// A rendered payload, ready to hand to any publish target.
#[derive(Debug, Clone, Default)]
pub struct Rendered {
    pub files: Vec<OutputFile>,
}

impl Rendered {
    fn push(&mut self, path: impl Into<String>, bytes: impl Into<Vec<u8>>) {
        self.files.push(OutputFile {
            path: path.into(),
            bytes: bytes.into(),
        });
    }
}

/// One row of the search index.
#[derive(Serialize)]
struct Searchable {
    n: u32,
    /// Title, summary, areas and body, lower-cased into one haystack. One field
    /// because the page does one thing with it.
    t: String,
}

/// Render the whole payload: the site, the feed, and the canonical document it
/// was all built from.
///
/// Entry pages are written as `{number}-{slug}/index.html`, so the URLs in
/// `log.json` resolve on any static host without rewrite rules.
pub fn render(log: &Log) -> Result<Rendered, serde_json::Error> {
    let mut rendered = Rendered::default();

    rendered.push("log.json", serde_json::to_vec_pretty(log)?);
    rendered.push("style.css", include_str!("assets/style.css"));
    rendered.push("search.js", include_str!("assets/search.js"));
    rendered.push("index.html", html::home(log));
    rendered.push("open/index.html", html::open_questions(log));
    if log.readme.is_some() {
        rendered.push("about/index.html", html::about(log));
    }
    if !log.docs.is_empty() {
        rendered.push("docs/index.html", html::docs_index(log));
        for doc in &log.docs {
            // The docs root's own README is already rendered as the index by
            // `docs_index`; giving it a page of its own writes `docs//`.
            if doc.slug.is_empty() {
                continue;
            }
            rendered.push(
                format!("docs/{}/index.html", doc.slug),
                html::doc_page(log, doc),
            );
        }
    }
    rendered.push("feed.xml", feed::atom(log));

    let by_number = log
        .entries
        .iter()
        .map(|entry| (entry.number, entry))
        .collect();
    for (at, entry) in log.entries.iter().enumerate() {
        rendered.push(
            format!("{}-{}/index.html", entry.number, entry.slug),
            html::entry(log, at, &by_number),
        );
    }

    let searchable: Vec<Searchable> = log
        .entries
        .iter()
        .map(|entry| Searchable {
            n: entry.number,
            t: format!(
                "{} {} {} {}",
                entry.title,
                entry.summary.clone().unwrap_or_default(),
                entry.areas.join(" "),
                html::plain(entry)
            )
            .to_lowercase(),
        })
        .collect();
    rendered.push("search.json", serde_json::to_vec(&searchable)?);

    Ok(rendered)
}

/// Render the index - `WORKLOG.md` - from the log.
///
/// Generated, and named as such in its own first lines, because the failure
/// mode it exists to prevent is somebody editing it to match what they think
/// the entries say.
pub fn render_index(log: &Log, header: Option<&str>) -> String {
    let mut out = String::new();

    match header {
        Some(written) => {
            out.push_str(written.trim_end());
            out.push_str("\n\n");
        }
        None => {
            out.push_str("# Worklog\n\n");
            if !log.project.description.is_empty() {
                out.push_str(&log.project.description);
                out.push_str("\n\n");
            }
            out.push_str(
                "One file per entry, newest at the bottom. This index is generated by \
                 `cairns index` - edit the entries, not this file.\n\n",
            );
        }
    }

    // Alphabetical, not declared order: this line is a tally, and a tally reads
    // better sorted by the name you would look for.
    let mut counted: Vec<_> = log.areas.iter().filter(|area| area.count > 0).collect();
    counted.sort_by(|a, b| a.name.cmp(&b.name));
    let tally = counted
        .iter()
        .map(|area| format!("{} {}", area.name, area.count))
        .collect::<Vec<_>>()
        .join(", ");
    let total = log.entries.len();
    let plural = if total == 1 { "entry" } else { "entries" };
    out.push_str(&format!("{total} {plural}: {tally}.\n\n"));

    out.push_str("| # | Entry | Date | Area |\n| ---: | --- | --- | --- |\n");
    for entry in &log.entries {
        let title = entry.title.replace('|', "\\|");
        out.push_str(&format!(
            "| {} | [{title}]({}) | {} | {} |\n",
            entry.number,
            entry.path,
            entry.date,
            entry.areas.join(", ")
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use cairns_core::{Config, Entry, RawEntry};

    fn log(entries: &[(&str, &str)]) -> Log {
        let config = Config::parse(
            r#"
            spec_version = 1
            [project]
            name = "A Project"
            slug = "a-project"
            description = "Testing."
            [site]
            base_url = "https://example.com/a-project/"
            [[area]]
            name = "spec"
            [[area]]
            name = "core"
            "#,
        )
        .unwrap();

        let parsed: Vec<Entry> = entries
            .iter()
            .enumerate()
            .map(|(at, (front, body))| {
                let number = at + 1;
                let text = format!("---\n{front}\n---\n\n# {number}. Title {number}\n\n{body}\n");
                Entry::parse(&RawEntry {
                    path: format!("worklog/{number:04}-title-{number}.md"),
                    bytes: text.into_bytes(),
                })
                .unwrap()
            })
            .collect();
        Log::build(&config, parsed, None)
    }

    fn simple() -> Log {
        log(&[(
            "number: 1\ntitle: Title 1\ndate: 2026-09-20\narea: spec",
            "Some prose.\n\n**Still unknown:** whether it works.",
        )])
    }

    #[test]
    fn a_payload_carries_the_site_and_the_document_it_came_from() {
        let rendered = render(&simple()).unwrap();
        let files: Vec<&str> = rendered.files.iter().map(|f| f.path.as_str()).collect();
        for wanted in [
            "log.json",
            "index.html",
            "style.css",
            "search.js",
            "search.json",
            "feed.xml",
            "open/index.html",
            "1-title-1/index.html",
        ] {
            assert!(files.contains(&wanted), "{wanted} missing from {files:?}");
        }
    }

    #[test]
    fn the_entry_page_renders_prose_once_and_the_trailer_separately() {
        let built = simple();
        let by_number = built.entries.iter().map(|e| (e.number, e)).collect();
        let page = html::entry(&built, 0, &by_number);
        // Once in the article. It also appears in the two meta descriptions,
        // because the summary is derived from the first sentence - which is
        // the point of deriving it, not a duplicate.
        assert_eq!(page.matches("<p>Some prose.</p>").count(), 1);
        assert_eq!(
            page.matches("og:description\" content=\"Some prose.")
                .count(),
            1
        );
        // Exactly one h1 per page, and it is the entry's title: the site name
        // in the rail is a link, not a competing heading.
        assert_eq!(page.matches("<h1>").count(), 1);
        assert!(page.contains("<h1>Title 1</h1>"), "{page}");
        assert!(page.contains("class=\"unknown\""));
        assert!(page.contains("whether it works."));
        assert!(
            !page.contains("**Still unknown:**"),
            "the marker leaked into the page"
        );
    }

    #[test]
    fn markdown_tables_and_code_render() {
        let built = log(&[(
            "number: 1\ntitle: Title 1\ndate: 2026-09-20\narea: spec",
            "| a | b |\n| --- | --- |\n| 1 | 2 |\n\n```\ncode\n```",
        )]);
        let by_number = built.entries.iter().map(|e| (e.number, e)).collect();
        let page = html::entry(&built, 0, &by_number);
        assert!(page.contains("<table>"), "tables are not enabled");
        assert!(page.contains("<pre>"), "code blocks are not rendering");
    }

    #[test]
    fn a_title_with_markup_in_it_cannot_escape_an_attribute() {
        let built = log(&[(
            "number: 1\ntitle: A \"quoted\" <script> & co\ndate: 2026-09-20\narea: spec",
            "Prose.",
        )]);
        let by_number = built.entries.iter().map(|e| (e.number, e)).collect();
        let page = html::entry(&built, 0, &by_number);
        assert!(
            !page.contains("<script>"),
            "an unescaped tag reached the page"
        );
        assert!(page.contains("&quot;quoted&quot;"));
    }

    #[test]
    fn a_correction_is_announced_on_the_entry_it_corrects() {
        let built = log(&[
            (
                "number: 1\ntitle: Title 1\ndate: 2026-09-20\narea: spec",
                "The wrong claim.",
            ),
            (
                "number: 2\ntitle: Title 2\ndate: 2026-09-21\narea: spec\nsupersedes: 1",
                "The right one.",
            ),
        ]);
        let by_number: std::collections::BTreeMap<_, _> =
            built.entries.iter().map(|e| (e.number, e)).collect();

        let overturned = html::entry(&built, 0, &by_number);
        assert!(overturned.contains("Revisited later"));
        assert!(overturned.contains("../2-title-2/"));

        let correcting = html::entry(&built, 1, &by_number);
        assert!(correcting.contains("revisits"));
        assert!(correcting.contains("../1-title-1/"));
    }

    #[test]
    fn the_feed_is_capped_and_points_at_the_whole_log() {
        let many: Vec<(String, String)> = (1..=30)
            .map(|n| {
                (
                    format!("number: {n}\ntitle: Title {n}\ndate: 2026-09-20\narea: spec"),
                    "Prose.".to_string(),
                )
            })
            .collect();
        let borrowed: Vec<(&str, &str)> =
            many.iter().map(|(f, b)| (f.as_str(), b.as_str())).collect();
        let xml = feed::atom(&log(&borrowed));
        assert_eq!(xml.matches("<entry>").count(), feed::FEED_ENTRIES);
        assert!(
            xml.contains("log.json"),
            "nothing points at the complete document"
        );
    }
}

#[cfg(test)]
mod docs_tests {
    use super::*;
    use cairns_core::{Config, Doc, Entry, RawEntry};

    fn built(paths: &[&str]) -> Log {
        let config = Config::parse(
            "spec_version = 1\n[project]\nname = \"P\"\nslug = \"p\"\n\
             [site]\nbase_url = \"https://example.com/p/\"\n\
             [docs]\ndir = \"docs\"\n[[area]]\nname = \"spec\"\n",
        )
        .unwrap();
        let entry = Entry::parse(&RawEntry {
            path: "worklog/0001-t.md".into(),
            bytes:
                b"---\nnumber: 1\ntitle: T\ndate: 2026-09-20\narea: spec\n---\n\n# 1. T\n\nProse.\n"
                    .to_vec(),
        })
        .unwrap();
        let docs: Vec<Doc> = paths
            .iter()
            .map(|path| {
                Doc::parse(&RawEntry {
                    path: (*path).into(),
                    bytes: format!("---\ntitle: {path}\n---\n\n# {path}\n\nProse.\n").into_bytes(),
                })
                .unwrap()
            })
            .collect();
        Log::build_with(&config, vec![entry], docs, None)
    }

    /// Hellbender's `docs/README.md` has an empty slug and an empty section, so
    /// it was its own parent and the tree recursed until the stack ran out.
    /// This renders it; a regression is a crash, not a failed assertion.
    #[test]
    fn a_docs_root_readme_is_not_its_own_parent() {
        let log = built(&["docs/README.md", "docs/formats/pod.md", "docs/port/plan.md"]);
        let rendered = render(&log).expect("renders");

        let paths: Vec<&str> = rendered.files.iter().map(|f| f.path.as_str()).collect();
        assert!(paths.contains(&"docs/index.html"));
        assert!(paths.contains(&"docs/formats/pod/index.html"));
        // The root README is the docs index, not a page of its own.
        assert!(
            !paths.iter().any(|path| path.contains("docs//")),
            "{paths:?}"
        );

        let index = rendered
            .files
            .iter()
            .find(|f| f.path == "docs/index.html")
            .unwrap();
        let html = String::from_utf8(index.bytes.clone()).unwrap();
        assert!(
            !html.contains("docs//"),
            "a link points at the docs root as a child"
        );
    }
}

#[cfg(test)]
mod reference_tests {
    use super::*;
    use cairns_core::{Config, Entry, RawEntry};

    fn page(body: &str) -> String {
        let config = Config::parse(
            "spec_version = 1\n[project]\nname = \"P\"\nslug = \"p\"\n\
             repository = \"https://example.com/p\"\n\
             [site]\nbase_url = \"https://example.com/p/\"\n[[area]]\nname = \"spec\"\n",
        )
        .unwrap();
        let entries: Vec<Entry> = [(1, "The first thing", "Prose."), (2, "The second", body)]
            .iter()
            .map(|(number, title, body)| {
                let text = format!(
                    "---\nnumber: {number}\ntitle: {title}\ndate: 2026-09-20\narea: spec\n---\n\n\
                     # {number}. {title}\n\n{body}\n\n**Still unknown:** nothing\n"
                );
                Entry::parse(&RawEntry {
                    path: format!("worklog/{number:04}-e{number}.md"),
                    bytes: text.into_bytes(),
                })
                .unwrap()
            })
            .collect();
        let log = Log::build(&config, entries, None);
        let by_number = log.entries.iter().map(|e| (e.number, e)).collect();
        html::entry(&log, 1, &by_number)
    }

    #[test]
    fn a_reference_becomes_a_link_carrying_the_entry_title() {
        let html = page("As [[1]] showed.");
        assert!(
            html.contains(r#"<a href="../1-the-first-thing/" title="The first thing">1</a>"#),
            "{html}"
        );
    }

    #[test]
    fn a_reference_may_supply_its_own_words() {
        let html = page("See [[1|the first thing we did]].");
        assert!(html.contains(">the first thing we did</a>"), "{html}");
    }

    /// The spec pages show `[[area]]` in fenced TOML, and a docs page that
    /// documents this syntax has to be able to print it.
    #[test]
    fn code_is_left_exactly_as_written() {
        let fenced = page("```toml\n[[area]]\nname = \"spec\"\n```");
        assert!(fenced.contains("[[area]]"), "a TOML table became a link");

        let inline = page("Write `[[1]]` to link to [[1]].");
        assert!(inline.contains("<code>[[1]]</code>"), "{inline}");
        // Count the reference form specifically - the pager also links to
        // entry 1, and an earlier version of this assertion counted that.
        assert_eq!(
            inline.matches(r#"title="The first thing">1</a>"#).count(),
            1
        );
    }

    #[test]
    fn a_reference_to_nothing_is_left_as_text() {
        let html = page("See [[999]].");
        assert!(html.contains("[[999]]"), "{html}");
    }
}
