# This repo is its own Homebrew tap:
#
#   brew tap Toyz/cairns https://github.com/Toyz/cairns
#   brew install cairns
#
# A formula rather than a cask: casks are macOS-only and aimed at .app and
# .pkg payloads, and cairns ships Linux binaries too.
#
# Generated by scripts/update-formula.sh on release - do not edit by hand.
class Cairns < Formula
  desc "Worklog kept as numbered markdown entries: write them, check them, publish them"
  homepage "https://github.com/Toyz/cairns"
  version "0.8.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "d1c41273af9797a90aac8882baa0e519617d3493dbbdb7c2961333161966a10f"
    end
    on_intel do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "f1c4f33f97c91995330ddca45f81378ada4b88fcfd086d5f51e534d9a84be5e3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8d693b4c3259750f150599f67c44aad7cd7271b02d61f9994995daf6375fa48f"
    end
  end

  # Each archive holds one top-level directory, which Homebrew enters before
  # running this, so the binary is just `cairns` from here.
  def install
    bin.install "cairns"
  end

  test do
    assert_match "cairns", shell_output("#{bin}/cairns --version")
  end
end
