# This repo is its own Homebrew tap:
#
#   brew tap Toyz/cairns https://github.com/Toyz/cairns
#   brew install cairns
#
# A formula rather than a cask: casks are macOS-only and aimed at .app and
# .pkg payloads, and cairns ships Linux binaries too.
#
# Generated by scripts/update-formula.sh on release - do not edit by hand.
class Cairns < Formula
  desc "Worklog kept as numbered markdown entries: write them, check them, publish them"
  homepage "https://github.com/Toyz/cairns"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "d917b3391fadb82eed9e341f3b9c384292a86cdfe3b568d70a9675180912fa0a"
    end
    on_intel do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "e336bc5a015db7bec2595a4fbab4782636142c5a855a54858f1d537d0e4be1e7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "b8cfe22055669506412ce0fda79fa567b47627eda16ff885e658aa349dc7509e"
    end
  end

  # Each archive holds one top-level directory, which Homebrew enters before
  # running this, so the binary is just `cairns` from here.
  def install
    bin.install "cairns"
  end

  test do
    assert_match "cairns", shell_output("#{bin}/cairns --version")
  end
end
