# This repo is its own Homebrew tap:
#
#   brew tap Toyz/cairns https://github.com/Toyz/cairns
#   brew install cairns
#
# A formula rather than a cask: casks are macOS-only and aimed at .app and
# .pkg payloads, and cairns ships Linux binaries too.
#
# Generated by scripts/update-formula.sh on release - do not edit by hand.
class Cairns < Formula
  desc "Worklog kept as numbered markdown entries: write them, check them, publish them"
  homepage "https://github.com/Toyz/cairns"
  version "0.5.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "3306eea330633e91f079bd635c223f3faace6b38c2384535e7448a68f552f104"
    end
    on_intel do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "40ac768d01ea011c0de1f69c814d3c5401699e74ec33c6a823a499b89a5ceb0b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8a6b01931dd8e498586c2a36e0387f33d046ce2b2da0b3a7c06e6de447c04eb4"
    end
  end

  # Each archive holds one top-level directory, which Homebrew enters before
  # running this, so the binary is just `cairns` from here.
  def install
    bin.install "cairns"
  end

  test do
    assert_match "cairns", shell_output("#{bin}/cairns --version")
  end
end
