#!/bin/sh
# Regenerate Formula/cairns.rb for a tag, from that release's SHA256SUMS.
#
#   scripts/update-formula.sh v0.3.0 SHA256SUMS
#
# It writes the whole file rather than patching lines in it. A formula that is
# edited in place drifts the moment a line moves; one that is generated cannot
# disagree with the release it was generated from.
set -eu

tag="${1:-}"
sums="${2:-}"
case "$tag" in
  v[0-9]*.[0-9]*.[0-9]*) ;;
  *) printf 'expected a vX.Y.Z tag, got %s\n' "${tag:-<nothing>}" >&2; exit 1 ;;
esac
[ -r "$sums" ] || { printf '%s is not readable\n' "$sums" >&2; exit 1; }

version="${tag#v}"

digest() {
  found=$(grep " cairns-$tag-$1\.tar\.gz\$" "$sums" | cut -d' ' -f1 | head -n1)
  [ -n "$found" ] || { printf 'no digest for %s in %s\n' "$1" "$sums" >&2; exit 1; }
  printf '%s' "$found"
}

arm_mac=$(digest aarch64-apple-darwin)
intel_mac=$(digest x86_64-apple-darwin)
linux=$(digest x86_64-unknown-linux-gnu)

cat > Formula/cairns.rb <<RUBY
# This repo is its own Homebrew tap:
#
#   brew tap Toyz/cairns https://github.com/Toyz/cairns
#   brew install cairns
#
# A formula rather than a cask: casks are macOS-only and aimed at .app and
# .pkg payloads, and cairns ships Linux binaries too.
#
# Generated by scripts/update-formula.sh on release - do not edit by hand.
class Cairns < Formula
  desc "Worklog kept as numbered markdown entries: write them, check them, publish them"
  homepage "https://github.com/Toyz/cairns"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "$arm_mac"
    end
    on_intel do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "$intel_mac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Toyz/cairns/releases/download/v#{version}/cairns-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux"
    end
  end

  # Each archive holds one top-level directory, which Homebrew enters before
  # running this, so the binary is just \`cairns\` from here.
  def install
    bin.install "cairns"
  end

  test do
    assert_match "cairns", shell_output("#{bin}/cairns --version")
  end
end
RUBY

printf 'Formula/cairns.rb -> %s\n' "$version"
